from pathlib import Path
root=Path(r'D:\github\NeonBreach\Assets\NeonBreach\Scripts')
p=root/'Gameplay/GameSession.cs'; s=p.read_text(encoding='utf-8-sig')
s=s.replace('bool heavy = Wave >= 2 && Random.value < 0.15f + Wave * 0.04f;\n            bool ranged', 'bool boss = Wave == FinalWave && Enemies.Count == 0 && pendingSpawns == WaveRules.EnemyCount(Wave);\n            bool heavy = boss || Wave >= 2 && Random.value < 0.15f + Wave * 0.04f;\n            bool ranged')
s=s.replace('var go = new GameObject(ranged ? "LANCER // Long-range" : heavy ? "BULWARK // Heavy" : "SENTRY // Rifleman");', 'var go = new GameObject(boss ? "OVERSEER // Command Unit" : ranged ? "LANCER // Long-range" : heavy ? "BULWARK // Heavy" : "SENTRY // Rifleman");')
s=s.replace('agent.Initialize(this, heavy, ranged);', 'agent.Initialize(this, heavy, ranged, boss);')
s=s.replace('int points = WaveRules.Score(enemy.Heavy, headshot);', 'int points = WaveRules.Score(enemy.Heavy, headshot) + (enemy.Boss ? 750 : 0);')
p.write_text(s,encoding='utf-8')
p=root/'Gameplay/EnemyAgent.cs'; s=p.read_text(encoding='utf-8-sig')
s=s.replace('public bool Ranged { get; private set; }','public bool Ranged { get; private set; }\n        public bool Boss { get; private set; }')
s=s.replace('public void Initialize(GameSession game, bool heavy, bool ranged = false)\n        {\n            session = game; Heavy = heavy; Ranged = ranged;', 'public void Initialize(GameSession game, bool heavy, bool ranged = false, bool boss = false)\n        {\n            session = game; Heavy = heavy; Ranged = ranged; Boss = boss;')
s=s.replace('WaveRules.Health(game.Wave, heavy) * game.EnemyHealthMultiplier * (ranged ? 0.82f : 1f)', 'WaveRules.Health(game.Wave, heavy) * game.EnemyHealthMultiplier * (boss ? 3.2f : ranged ? 0.82f : 1f)')
s=s.replace('controller.center = new Vector3(0, 0.85f, 0);', 'controller.center = new Vector3(0, 0.85f, 0);\n            if (Boss) { controller.height = 2.4f; controller.radius = 0.58f; transform.localScale = Vector3.one * 1.35f; }')
s=s.replace('game.World.White : game.World.Metal', 'game.World.White : game.World.Metal')
s=s.replace('heavy ? game.World.Amber : ranged ? game.World.White : game.World.Metal', 'boss ? game.World.Red : heavy ? game.World.Amber : ranged ? game.World.White : game.World.Metal')
s=s.replace('if (distance < (Ranged ? 17 : 6))', 'if (distance < (Boss ? 9 : Ranged ? 17 : 6))')
s=s.replace('attackCooldown = Heavy ? 1.2f : Ranged ? 2.4f : 1.65f;', 'attackCooldown = Boss ? 0.85f : Heavy ? 1.2f : Ranged ? 2.4f : 1.65f;')
s=s.replace('windup = Heavy ? 0.6f : Ranged ? 0.85f : 0.48f;', 'windup = Boss ? 0.72f : Heavy ? 0.6f : Ranged ? 0.85f : 0.48f;')
s=s.replace('if (attackCooldown <= 0 && seesPlayer && distance < (Ranged ? 48 : 27))', 'if (attackCooldown <= 0 && seesPlayer && distance < (Boss ? 38 : Ranged ? 48 : 27))')
s=s.replace('Heavy ? 0.28f : Ranged ? 0.16f : 0.43f', 'Boss ? 0.20f : Heavy ? 0.28f : Ranged ? 0.16f : 0.43f')
s=s.replace('WaveRules.Damage(session.Wave, Heavy) * session.EnemyDamageMultiplier', 'WaveRules.Damage(session.Wave, Heavy) * session.EnemyDamageMultiplier * (Boss ? 1.5f : 1f)')
p.write_text(s,encoding='utf-8')
p=root/'Presentation/ArenaHud.cs'; s=p.read_text(encoding='utf-8-sig')
s=s.replace('Text(1270, 765, 270, 22, "VX-07  /  ION RIFLE"', 'Text(1270, 765, 270, 22, "VX-07  /  ION RIFLE"')
s=s.replace('if (session.State == MatchState.Playing && Time.time < session.KillNoticeUntil)', 'if (session.State == MatchState.Playing && session.Wave == 5 && session.Remaining > 0) Text(565, 113, 470, 25, "FINAL WAVE  /  OVERSEER ACTIVE", 13, ArenaWorld.Orange, FontStyle.Bold, TextAnchor.UpperCenter);\n            if (session.State == MatchState.Playing && Time.time < session.KillNoticeUntil)')
p.write_text(s,encoding='utf-8')
p=Path(r'D:\github\NeonBreach\README.md'); s=p.read_text(encoding='utf-8-sig')
s=s.replace('五波战斗；支持训练、标准、极限三档难度。','五波战斗；支持训练、标准、极限三档难度。第 5 波会出现 OVERSEER 指挥型 Boss。')
p.write_text(s,encoding='utf-8')
