from pathlib import Path
root=Path(r'D:\github\NeonBreach\Assets\NeonBreach\Scripts')
p=root/'Gameplay/RifleController.cs'; s=p.read_text(encoding='utf-8-sig')
s=s.replace('public float Bloom { get; private set; }','public float Bloom { get; private set; }\n        public bool Automatic { get; private set; } = true;')
s=s.replace('if (Input.GetKeyDown(KeyCode.R)) Reload();','if (Input.GetKeyDown(KeyCode.V)) { Automatic = !Automatic; session.Announce(Automatic ? "FIRE MODE  /  FULL AUTO" : "FIRE MODE  /  SEMI AUTO", 1.2f); session.Audio.Play(SoundCue.Wave, 0.25f); }\n            if (Input.GetKeyDown(KeyCode.R)) Reload();')
s=s.replace('if (Input.GetMouseButton(0) && cooldown <= 0 && !Ammo.Reloading)', 'if ((Automatic ? Input.GetMouseButton(0) : Input.GetMouseButtonDown(0)) && cooldown <= 0 && !Ammo.Reloading)')
p.write_text(s,encoding='utf-8')
p=root/'Presentation/ArenaHud.cs'; s=p.read_text(encoding='utf-8-sig')
s=s.replace('Text(1270, 848, 270, 20, ammo.Reloading ? "RELOADING ..." : "FULL AUTO   /   R TO RELOAD"', 'Text(1270, 848, 270, 20, ammo.Reloading ? "RELOADING ..." : (player.Weapon.Automatic ? "FULL AUTO" : "SEMI AUTO") + "   /   V TO TOGGLE"')
s=s.replace('ALT  AIM      G  GRENADE      R  RELOAD', 'ALT  AIM      G  GRENADE      V  FIRE MODE      R  RELOAD')
p.write_text(s,encoding='utf-8')
p=Path(r'D:\github\NeonBreach\README.md'); s=p.read_text(encoding='utf-8-sig')
s=s.replace('| R | 换弹 |','| R | 换弹 |\n| V | 全自动 / 半自动切换 |')
s=s.replace('左 Shift 冲刺 | C 蹲伏 | G 手雷 | Space 跳跃', '左 Shift 冲刺 | C 蹲伏 | G 手雷 | V 射击模式 | Space 跳跃')
p.write_text(s,encoding='utf-8')
