from pathlib import Path
root=Path(r'D:\github\NeonBreach\Assets\NeonBreach\Scripts')
p=root/'Gameplay/GameSession.cs'; s=p.read_text(encoding='utf-8-sig')
s=s.replace('bool heavy = Wave >= 2 && Random.value < 0.15f + Wave * 0.04f;\n            var go = new GameObject(heavy ? "BULWARK // Heavy" : "SENTRY // Rifleman");', 'bool heavy = Wave >= 2 && Random.value < 0.15f + Wave * 0.04f;\n            bool ranged = !heavy && Wave >= 2 && Random.value < 0.18f;\n            var go = new GameObject(ranged ? "LANCER // Long-range" : heavy ? "BULWARK // Heavy" : "SENTRY // Rifleman");')
s=s.replace('agent.Initialize(this, heavy);', 'agent.Initialize(this, heavy, ranged);')
p.write_text(s,encoding='utf-8')
p=root/'Gameplay/EnemyAgent.cs'; s=p.read_text(encoding='utf-8-sig')
s=s.replace('public bool Heavy { get; private set; }','public bool Heavy { get; private set; }\n        public bool Ranged { get; private set; }')
s=s.replace('public void Initialize(GameSession game, bool heavy)\n        {\n            session = game; Heavy = heavy;', 'public void Initialize(GameSession game, bool heavy, bool ranged = false)\n        {\n            session = game; Heavy = heavy; Ranged = ranged;')
s=s.replace('MaxHealth = Health = WaveRules.Health(game.Wave, heavy) * game.EnemyHealthMultiplier;', 'MaxHealth = Health = WaveRules.Health(game.Wave, heavy) * game.EnemyHealthMultiplier * (ranged ? 0.82f : 1f);')
s=s.replace('heavy ? game.World.Amber : game.World.Metal', 'heavy ? game.World.Amber : ranged ? game.World.White : game.World.Metal')
s=s.replace('if (!seesPlayer || distance > (Heavy ? 13 : 16))', 'if (!seesPlayer || distance > (Heavy ? 13 : Ranged ? 23 : 16))')
s=s.replace('if (distance < 6) movement -= transform.forward * 0.7f;', 'if (distance < (Ranged ? 17 : 6)) movement -= transform.forward * (Ranged ? 0.9f : 0.7f);\n                if (Ranged && distance > 25) movement += transform.forward * 0.6f;')
s=s.replace('if (attackCooldown <= 0 && seesPlayer && distance < 27)', 'if (attackCooldown <= 0 && seesPlayer && distance < (Ranged ? 48 : 27))')
s=s.replace('lockedTarget = aimAt + Random.insideUnitSphere * (Heavy ? 0.28f : 0.43f);\n                    windup = Heavy ? 0.6f : 0.48f;', 'lockedTarget = aimAt + Random.insideUnitSphere * (Heavy ? 0.28f : Ranged ? 0.16f : 0.43f);\n                    windup = Heavy ? 0.6f : Ranged ? 0.85f : 0.48f;')
s=s.replace('attackCooldown = Heavy ? 1.2f : 1.65f;', 'attackCooldown = Heavy ? 1.2f : Ranged ? 2.4f : 1.65f;')
s=s.replace('new Vector3(0.43f, 1.03f, 0.4f), new Vector3(0.16f, 0.19f, 0.75f), game.World.Dark', 'new Vector3(0.43f, 1.03f, 0.4f), new Vector3(0.16f, 0.19f, 0.75f), ranged ? game.World.White : game.World.Dark')
p.write_text(s,encoding='utf-8')
p=root/'Assets/NeonBreach/Scripts/World/ArenaWorld.cs' if False else root/'World/ArenaWorld.cs'; s=p.read_text(encoding='utf-8-sig')
needle='Cover(new Vector3(6, 0, 3), new Vector3(3, 1.25f, 2.5f));'
s=s.replace(needle, needle+'''\n            // Secondary lanes and elevated sightline structures create alternate flanking routes.\n            Cover(new Vector3(-20, 0, 11), new Vector3(4, 2.2f, 2.5f));\n            Cover(new Vector3(20, 0, -11), new Vector3(4, 2.2f, 2.5f));\n            Cover(new Vector3(-2, 0, 20), new Vector3(8, 1.8f, 2.2f));\n            Cover(new Vector3(2, 0, -20), new Vector3(8, 1.8f, 2.2f));\n            Box("North catwalk", new Vector3(0, 4.4f, 15), new Vector3(12, 0.35f, 2.4f), Metal);\n            Box("South catwalk", new Vector3(0, 4.4f, -15), new Vector3(12, 0.35f, 2.4f), Metal);\n            Box("Catwalk rail", new Vector3(-6, 5.1f, 15), new Vector3(0.18f, 1.2f, 2.4f), Teal, false);\n            Box("Catwalk rail", new Vector3(6, 5.1f, -15), new Vector3(0.18f, 1.2f, 2.4f), Amber, false);''')
p.write_text(s,encoding='utf-8')
