from pathlib import Path
root=Path(r'D:\github\NeonBreach\Assets\NeonBreach\Scripts')
p=root/'Gameplay/GameSession.cs'; s=p.read_text(encoding='utf-8-sig')
s=s.replace('public int Grenades { get; private set; } = 3;', 'public int Grenades { get; private set; } = 3;\n        public int KillStreak { get; private set; }\n        public int BestKillStreak { get; private set; }')
s=s.replace('Enemies.Clear(); Effects.Clear(); Grenades = 3; GrenadeCooldown = 0; ShotsFired', 'Enemies.Clear(); Effects.Clear(); Grenades = 3; GrenadeCooldown = 0; KillStreak = BestKillStreak = 0; ShotsFired')
s=s.replace('Player.Heal(25); Player.Weapon.Ammo.Supply(75);', 'Player.Heal(25); Player.Weapon.Ammo.Supply(75); Grenades = Mathf.Min(5, Grenades + 1);')
s=s.replace('Kills++; if (headshot) Headshots++;', 'Kills++; KillStreak++; BestKillStreak = Mathf.Max(BestKillStreak, KillStreak); if (headshot) Headshots++;')
s=s.replace('int points = WaveRules.Score(enemy.Heavy, headshot); Score += points;', 'int points = WaveRules.Score(enemy.Heavy, headshot);\n            int streakBonus = Mathf.Min(300, Mathf.Max(0, KillStreak - 1) * 15);\n            Score += points + streakBonus;')
s=s.replace('"  +" + points;', '"  +" + (points + streakBonus) + (streakBonus > 0 ? "  /  STREAK x" + KillStreak : "");')
s=s.replace('if (Player.Weapon.Ammo.Reserve < 45 || Random.value < 0.30f)', 'if (KillStreak >= 5 || Player.Weapon.Ammo.Reserve < 45 || Random.value < 0.30f)')
p.write_text(s,encoding='utf-8')
p=root/'Presentation/ArenaHud.cs'; s=p.read_text(encoding='utf-8-sig')
s=s.replace('Text(540, 851, 520, 22, "G  GRENADE (" + session.Grenades + ")', 'Text(540, 827, 520, 22, "KILL STREAK  /  x" + session.KillStreak + "    ACCURACY  " + session.Accuracy.ToString("F0") + "%", 10, session.KillStreak >= 3 ? ArenaWorld.Orange : muted, FontStyle.Normal, TextAnchor.UpperCenter);\n            Text(540, 851, 520, 22, "G  GRENADE (" + session.Grenades + ")')
s=s.replace('ACCURACY  " + session.Accuracy.ToString("F0") + "%    /    SHOTS', 'ACCURACY  " + session.Accuracy.ToString("F0") + "%    /    BEST STREAK  " + session.BestKillStreak + "    /    SHOTS')
p.write_text(s,encoding='utf-8')
